<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<!DOCTYPE hierarchy [
        <!ELEMENT hierarchy (node)*>
        <!ATTLIST hierarchy
                rotation CDATA #REQUIRED>
        <!ELEMENT node (node)*>
        <!ATTLIST node
                NAF CDATA #IMPLIED
                bounds CDATA #REQUIRED
                checkable CDATA #REQUIRED
                checked CDATA #REQUIRED
                class CDATA #REQUIRED
                clickable CDATA #REQUIRED
                content-desc CDATA #REQUIRED
                enabled CDATA #REQUIRED
                focusable CDATA #REQUIRED
                focused CDATA #REQUIRED
                index CDATA #REQUIRED
                long-clickable CDATA #REQUIRED
                package CDATA #REQUIRED
                password CDATA #REQUIRED
                resource-id CDATA #REQUIRED
                scrollable CDATA #REQUIRED
                selected CDATA #REQUIRED
                text CDATA #REQUIRED>
        ]>
<hierarchy rotation="0">
    <node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="com.xueqiu.android"
          content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false"
          focused="false" scrollable="false" long-clickable="false" password="false" selected="false"
          bounds="[0,0][1080,2028]">
        <node index="0" text="" resource-id="" class="android.widget.LinearLayout" package="com.xueqiu.android"
              content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false"
              focused="false" scrollable="false" long-clickable="false" password="false" selected="false"
              bounds="[0,0][1080,2028]">
            <node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="com.xueqiu.android"
                  content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false"
                  focused="false" scrollable="false" long-clickable="false" password="false" selected="false"
                  bounds="[0,0][1080,2028]">
                <node index="0" text="" resource-id="com.xueqiu.android:id/decor_content_parent"
                      class="android.view.ViewGroup" package="com.xueqiu.android" content-desc="" checkable="false"
                      checked="false" clickable="false" enabled="true" focusable="false" focused="false"
                      scrollable="false" long-clickable="false" password="false" selected="false"
                      bounds="[0,0][1080,2028]">
                    <node index="0" text="" resource-id="android:id/content" class="android.widget.FrameLayout"
                          package="com.xueqiu.android" content-desc="" checkable="false" checked="false"
                          clickable="false" enabled="true" focusable="false" focused="false" scrollable="false"
                          long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2028]">
                        <node index="0" text="" resource-id="" class="android.widget.LinearLayout"
                              package="com.xueqiu.android" content-desc="" checkable="false" checked="false"
                              clickable="false" enabled="true" focusable="false" focused="false" scrollable="false"
                              long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2028]">
                            <node index="0" text="" resource-id="" class="android.widget.FrameLayout"
                                  package="com.xueqiu.android" content-desc="" checkable="false" checked="false"
                                  clickable="false" enabled="true" focusable="false" focused="false" scrollable="false"
                                  long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1896]">
                                <node index="0" text="" resource-id="com.xueqiu.android:id/mainContent"
                                      class="android.widget.FrameLayout" package="com.xueqiu.android" content-desc=""
                                      checkable="false" checked="false" clickable="false" enabled="true"
                                      focusable="false" focused="false" scrollable="false" long-clickable="false"
                                      password="false" selected="false" bounds="[0,0][1080,1896]">
                                    <node index="0" text="" resource-id="" class="android.widget.LinearLayout"
                                          package="com.xueqiu.android" content-desc="" checkable="false" checked="false"
                                          clickable="false" enabled="true" focusable="false" focused="false"
                                          scrollable="false" long-clickable="false" password="false" selected="false"
                                          bounds="[0,0][1080,1896]">
                                        <node index="0" text="" resource-id="com.xueqiu.android:id/portfolio_action_bar"
                                              class="android.widget.RelativeLayout" package="com.xueqiu.android"
                                              content-desc="" checkable="false" checked="false" clickable="false"
                                              enabled="true" focusable="false" focused="false" scrollable="false"
                                              long-clickable="false" password="false" selected="false"
                                              bounds="[0,0][1080,220]">
                                            <node index="0" text="" resource-id="com.xueqiu.android:id/magic_indicator"
                                                  class="android.widget.FrameLayout" package="com.xueqiu.android"
                                                  content-desc="" checkable="false" checked="false" clickable="false"
                                                  enabled="true" focusable="false" focused="false" scrollable="false"
                                                  long-clickable="false" password="false" selected="false"
                                                  bounds="[0,66][750,220]">
                                                <node index="0" text="" resource-id=""
                                                      class="android.widget.FrameLayout" package="com.xueqiu.android"
                                                      content-desc="" checkable="false" checked="false"
                                                      clickable="false" enabled="true" focusable="false" focused="false"
                                                      scrollable="false" long-clickable="false" password="false"
                                                      selected="false" bounds="[3,66][750,179]">
                                                    <node index="0" text=""
                                                          resource-id="com.xueqiu.android:id/scroll_view"
                                                          class="android.widget.HorizontalScrollView"
                                                          package="com.xueqiu.android" content-desc="" checkable="false"
                                                          checked="false" clickable="false" enabled="true"
                                                          focusable="true" focused="false" scrollable="false"
                                                          long-clickable="false" password="false" selected="false"
                                                          bounds="[3,66][750,179]">
                                                        <node index="0" text="" resource-id=""
                                                              class="android.widget.FrameLayout"
                                                              package="com.xueqiu.android" content-desc=""
                                                              checkable="false" checked="false" clickable="false"
                                                              enabled="true" focusable="false" focused="false"
                                                              scrollable="false" long-clickable="false" password="false"
                                                              selected="false" bounds="[3,66][427,179]">
                                                            <node index="0" text=""
                                                                  resource-id="com.xueqiu.android:id/title_container"
                                                                  class="android.widget.LinearLayout"
                                                                  package="com.xueqiu.android" content-desc=""
                                                                  checkable="false" checked="false" clickable="false"
                                                                  enabled="true" focusable="false" focused="false"
                                                                  scrollable="false" long-clickable="false"
                                                                  password="false" selected="false"
                                                                  bounds="[3,66][427,179]">
                                                                <node index="0" text="" resource-id=""
                                                                      class="android.widget.FrameLayout"
                                                                      package="com.xueqiu.android" content-desc=""
                                                                      checkable="false" checked="false" clickable="true"
                                                                      enabled="true" focusable="false" focused="false"
                                                                      scrollable="false" long-clickable="false"
                                                                      password="false" selected="false"
                                                                      bounds="[3,66][239,179]">
                                                                    <node index="0" text="" resource-id=""
                                                                          class="android.widget.LinearLayout"
                                                                          package="com.xueqiu.android" content-desc=""
                                                                          checkable="false" checked="false"
                                                                          clickable="false" enabled="true"
                                                                          focusable="false" focused="false"
                                                                          scrollable="false" long-clickable="false"
                                                                          password="false" selected="false"
                                                                          bounds="[3,66][239,179]">
                                                                        <node index="0" text="" resource-id=""
                                                                              class="android.widget.FrameLayout"
                                                                              package="com.xueqiu.android"
                                                                              content-desc="" checkable="false"
                                                                              checked="false" clickable="false"
                                                                              enabled="true" focusable="false"
                                                                              focused="false" scrollable="false"
                                                                              long-clickable="false" password="false"
                                                                              selected="false"
                                                                              bounds="[31,66][211,179]">
                                                                            <node index="0" text="自选组合"
                                                                                  resource-id="com.xueqiu.android:id/title_text"
                                                                                  class="android.widget.TextView"
                                                                                  package="com.xueqiu.android"
                                                                                  content-desc="" checkable="false"
                                                                                  checked="false" clickable="false"
                                                                                  enabled="true" focusable="false"
                                                                                  focused="false" scrollable="false"
                                                                                  long-clickable="false"
                                                                                  password="false" selected="false"
                                                                                  bounds="[39,66][203,179]"/>
                                                                        </node>
                                                                        <node index="1" text=""
                                                                              resource-id="com.xueqiu.android:id/marker_container"
                                                                              class="android.widget.FrameLayout"
                                                                              package="com.xueqiu.android"
                                                                              content-desc="" checkable="false"
                                                                              checked="false" clickable="false"
                                                                              enabled="true" focusable="false"
                                                                              focused="false" scrollable="false"
                                                                              long-clickable="false" password="false"
                                                                              selected="false"
                                                                              bounds="[216,66][239,179]"/>
                                                                    </node>
                                                                </node>
                                                                <node index="1" text="" resource-id=""
                                                                      class="android.widget.FrameLayout"
                                                                      package="com.xueqiu.android" content-desc=""
                                                                      checkable="false" checked="false" clickable="true"
                                                                      enabled="true" focusable="false" focused="false"
                                                                      scrollable="false" long-clickable="false"
                                                                      password="false" selected="false"
                                                                      bounds="[239,66][427,179]">
                                                                    <node index="0" text="" resource-id=""
                                                                          class="android.widget.LinearLayout"
                                                                          package="com.xueqiu.android" content-desc=""
                                                                          checkable="false" checked="false"
                                                                          clickable="false" enabled="true"
                                                                          focusable="false" focused="false"
                                                                          scrollable="false" long-clickable="false"
                                                                          password="false" selected="false"
                                                                          bounds="[239,66][427,179]">
                                                                        <node index="0" text="" resource-id=""
                                                                              class="android.widget.FrameLayout"
                                                                              package="com.xueqiu.android"
                                                                              content-desc="" checkable="false"
                                                                              checked="false" clickable="false"
                                                                              enabled="true" focusable="false"
                                                                              focused="false" scrollable="false"
                                                                              long-clickable="false" password="false"
                                                                              selected="false"
                                                                              bounds="[267,66][399,179]">
                                                                            <node index="0" text="市场"
                                                                                  resource-id="com.xueqiu.android:id/title_text"
                                                                                  class="android.widget.TextView"
                                                                                  package="com.xueqiu.android"
                                                                                  content-desc="" checkable="false"
                                                                                  checked="false" clickable="false"
                                                                                  enabled="true" focusable="false"
                                                                                  focused="false" scrollable="false"
                                                                                  long-clickable="false"
                                                                                  password="false" selected="false"
                                                                                  bounds="[267,66][399,179]"/>
                                                                        </node>
                                                                        <node index="1" text=""
                                                                              resource-id="com.xueqiu.android:id/marker_container"
                                                                              class="android.widget.FrameLayout"
                                                                              package="com.xueqiu.android"
                                                                              content-desc="" checkable="false"
                                                                              checked="false" clickable="false"
                                                                              enabled="true" focusable="false"
                                                                              focused="false" scrollable="false"
                                                                              long-clickable="false" password="false"
                                                                              selected="false"
                                                                              bounds="[404,66][427,179]"/>
                                                                    </node>
                                                                </node>
                                                            </node>
                                                            <node index="1" text=""
                                                                  resource-id="com.xueqiu.android:id/indicator_container"
                                                                  class="android.widget.LinearLayout"
                                                                  package="com.xueqiu.android" content-desc=""
                                                                  checkable="false" checked="false" clickable="false"
                                                                  enabled="true" focusable="false" focused="false"
                                                                  scrollable="false" long-clickable="false"
                                                                  password="false" selected="false"
                                                                  bounds="[3,66][427,179]"/>
                                                        </node>
                                                    </node>
                                                </node>
                                            </node>
                                            <node index="1" text="" resource-id="com.xueqiu.android:id/ll_icon"
                                                  class="android.widget.LinearLayout" package="com.xueqiu.android"
                                                  content-desc="" checkable="false" checked="false" clickable="false"
                                                  enabled="true" focusable="false" focused="false" scrollable="false"
                                                  long-clickable="false" password="false" selected="false"
                                                  bounds="[750,66][1080,220]">
                                                <node NAF="true" index="0" text=""
                                                      resource-id="com.xueqiu.android:id/action_search"
                                                      class="android.widget.ImageButton" package="com.xueqiu.android"
                                                      content-desc="" checkable="false" checked="false" clickable="true"
                                                      enabled="true" focusable="true" focused="false" scrollable="false"
                                                      long-clickable="false" password="false" selected="false"
                                                      bounds="[764,66][896,220]"/>
                                                <node index="1" text="" resource-id=""
                                                      class="android.widget.RelativeLayout" package="com.xueqiu.android"
                                                      content-desc="" checkable="false" checked="false"
                                                      clickable="false" enabled="true" focusable="false" focused="false"
                                                      scrollable="false" long-clickable="false" password="false"
                                                      selected="false" bounds="[896,66][1041,220]">
                                                    <node NAF="true" index="0" text=""
                                                          resource-id="com.xueqiu.android:id/action_message"
                                                          class="android.widget.ImageButton"
                                                          package="com.xueqiu.android" content-desc="" checkable="false"
                                                          checked="false" clickable="true" enabled="true"
                                                          focusable="true" focused="false" scrollable="false"
                                                          long-clickable="false" password="false" selected="false"
                                                          bounds="[896,66][1028,220]"/>
                                                    <node index="1" text=""
                                                          resource-id="com.xueqiu.android:id/unread_count"
                                                          class="android.widget.ImageView" package="com.xueqiu.android"
                                                          content-desc="" checkable="false" checked="false"
                                                          clickable="false" enabled="true" focusable="false"
                                                          focused="false" scrollable="false" long-clickable="false"
                                                          password="false" selected="false"
                                                          bounds="[977,105][1041,146]"/>
                                                </node>
                                            </node>
                                        </node>
                                        <node index="1" text="" resource-id="com.xueqiu.android:id/viewpager"
                                              class="androidx.viewpager.widget.ViewPager" package="com.xueqiu.android"
                                              content-desc="" checkable="false" checked="false" clickable="false"
                                              enabled="true" focusable="true" focused="false" scrollable="true"
                                              long-clickable="false" password="false" selected="false"
                                              bounds="[0,220][1080,1896]">
                                            <node index="1" text="" resource-id="com.xueqiu.android:id/root_view"
                                                  class="android.widget.FrameLayout" package="com.xueqiu.android"
                                                  content-desc="" checkable="false" checked="false" clickable="false"
                                                  enabled="true" focusable="false" focused="false" scrollable="false"
                                                  long-clickable="false" password="false" selected="false"
                                                  bounds="[0,220][1080,1896]">
                                                <node index="0" text="" resource-id=""
                                                      class="android.widget.LinearLayout" package="com.xueqiu.android"
                                                      content-desc="" checkable="false" checked="false"
                                                      clickable="false" enabled="true" focusable="false" focused="false"
                                                      scrollable="false" long-clickable="false" password="false"
                                                      selected="false" bounds="[0,220][1080,1896]">
                                                    <node index="0" text=""
                                                          resource-id="com.xueqiu.android:id/indicator"
                                                          class="android.widget.FrameLayout"
                                                          package="com.xueqiu.android" content-desc="" checkable="false"
                                                          checked="false" clickable="false" enabled="true"
                                                          focusable="false" focused="false" scrollable="false"
                                                          long-clickable="false" password="false" selected="false"
                                                          bounds="[0,220][1080,330]">
                                                        <node index="0" text="" resource-id=""
                                                              class="android.widget.FrameLayout"
                                                              package="com.xueqiu.android" content-desc=""
                                                              checkable="false" checked="false" clickable="false"
                                                              enabled="true" focusable="false" focused="false"
                                                              scrollable="false" long-clickable="false" password="false"
                                                              selected="false" bounds="[0,220][1080,330]">
                                                            <node index="0" text="" resource-id=""
                                                                  class="android.widget.FrameLayout"
                                                                  package="com.xueqiu.android" content-desc=""
                                                                  checkable="false" checked="false" clickable="false"
                                                                  enabled="true" focusable="false" focused="false"
                                                                  scrollable="false" long-clickable="false"